label: Vertaling
tips:
  locale-overview:
    label: Gebruikersinterface-vertaling
    body: 'Deze pagina maakt het mogelijk om de gebruikersinterface te vertalen of bestaande vertalingen aan te passen. Als u de site in eerste instantie in het Engels heeft geïnstalleerd, dan moet u eerst een andere taal toevoegen op de  <a href="[site:url]admin/config/regional/language">Talen pagina</a>, om deze pagina te kunnen gebruiken.'
  locale-language:
    label: Vertalingstaal
    body: 'Kies de taal die u wilt vertalen.'
  locale-search:
    label: Zoeken
    body: 'Geef het specifieke woord of zin op dat u wilt vertalen. U kunt ook alleen een deel van een woord opgeven.'
  locale-filter:
    label: 'Zoekresultaten filteren'
    body: 'U kunt zoeken op onvertaalde tekenreeksen als u iets wilt vertalen dat nog niet is vertaald. Als u een bestaande vertaling wilt aanpassen, dan kunt u ook alleen zoeken op vertaalde tekenreeksen.'
  locale-submit:
    label: 'De zoekcriteria toepassen'
    body: 'Klik op de <em>Filter</em>-knop om de zoekcriteria toe te passen.'
  locale-translate:
    label: Vertalen
    body: 'U kunt uw eigen vertaling in de tekstvelden van de rechter kolom schrijven. U kunt het beste proberen te achterhalen in welke context de tekst wordt gebruikt om de meest passende vertaling te geven.'
  locale-validate:
    label: 'De vertaling valideren'
    body: 'Als u klaar bent met de vertaling klikt u op de knop <em>Vertalingen opslaan</em>. U moet de vertaling opslaan voordat u de pagina wisselt of een nieuwe zoekopdracht uitvoert.'
  locale-continue:
    label: 'Wordt vervolgd op'
    body: 'De vertalingen die u hier heeft gedaan worden gebruikt in de gebruikersinterface van de site. Als u ze op een andere site wilt gebruiken of met een externe vertaaleditor wilt aanpassen dan kunt u deze <a href="[site:url]admin/config/regional/translate/export">exporteren</a> naar een .po-bestand en ze later weer <a href="[site:url]admin/config/regional/translate/import">importeren</a>.'
