label: 'Talen bewerken'
tips:
  language-edit-overview:
    label: 'Talen bewerken'
    body: '<p> Deze pagina biedt de mogelijkheid om een taal te bewerken op uw site, inclusief aangepaste talen. </p>'
  language-edit-langcode:
    label: Taalcode
    body: '<p>U kunt de taalcode niet aanpassen op de site omdat deze gebruikt wordt door het systeem om de taal te identificeren.</p>'
  language-edit-label:
    label: Taalnaam
    body: '<p>De naam van de taal wordt site-breed gebruikt voor alle gebruikers en wordt in het Engels weergegeven. Namen van ingebouwde talen kunnen vertaald worden met de Interface Translation-module en namen van zowel ingebouwde als aangepaste talen kunnen met de Configuration Translation-module vertaald worden.</p>'
  language-edit-direction:
    label: Taalrichting
    body: '<p>Kies of de schrijfrichting van de taal ''links naar rechts'' of ''rechts naar links'' is.</p><p>Merk op dat niet alle thema''s ''rechts naar links''-layouts ondersteunen dus test het thema bij het gebruik van ''rechts naar links".</p>'
  language-edit-continue:
    label: 'Wordt vervolgd op'
